"use client";
import ThemeToggle from "./ThemeToggle";
import dynamic from "next/dynamic";import Link from "next/link";import {useEffect,useMemo,useState} from "react";import {AlertTriangle,BarChart3,Check,ChevronDown,Compass,Download,Hospital,Layers3,LoaderCircle,Map,MapPin,ShieldCheck} from "lucide-react";import {health,pinRisk,policyDeserts} from "@/lib/api";import {INDIA_STATES,STATE_CENTROIDS} from "@/lib/india";import type {TrustPin} from "./DesertLeafletMap";
const LeafletMap=dynamic(()=>import("./DesertLeafletMap"),{ssr:false});const SPECS=["emergency","cardiology","ophthalmology","orthopedics","obgyn","pediatrics","oncology","neurology","dialysis","trauma","icu","surgery","dentistry","psychiatry","neonatology"];
type Json=Record<string,any>;type Mode="coverage"|"hotspot"|"trust";
export default function DesertMapDashboard(){const[ok,setOk]=useState<boolean|null>(null),[mode,setMode]=useState<Mode>("coverage"),[spec,setSpec]=useState("cardiology"),[level,setLevel]=useState<"state"|"pin">("state"),[selected,setSelected]=useState<string[]>([]),[pin,setPin]=useState(""),[spotlight,setSpotlight]=useState<{pin:string;state:string}|undefined>(),[data,setData]=useState<Json|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(""),[trustPins,setTrustPins]=useState<TrustPin[]>([]);
 useEffect(()=>{setTrustPins(loadTrustPins());health().then(x=>setOk(Boolean(x.ok))).catch(()=>setOk(false))},[]);useEffect(()=>{let live=true;setBusy(true);setError("");policyDeserts(spec,level).then(x=>{if(live)setData(x)}).catch(e=>{if(live)setError(e instanceof Error?e.message:"Coverage unavailable")}).finally(()=>{if(live)setBusy(false)});return()=>{live=false}},[spec,level]);
 const rawDeserts=useMemo(()=>cleanStates(data?.desert_states),[data]),deserts=selected.length?rawDeserts.filter(x=>selected.includes(x)):rawDeserts,covered=useMemo(()=>INDIA_STATES.filter(x=>!rawDeserts.includes(x)),[rawDeserts]),shownCovered=selected.length?covered.filter(x=>selected.includes(x)):covered,pins=useMemo(()=>(Array.isArray(data?.desert_pins)?data!.desert_pins:[]).map(String).filter(Boolean),[data]);const pinCounts=useMemo(()=>distribute(deserts,pins.length),[deserts,pins.length]);
 async function locatePin(){if(!/^\d{6}$/.test(pin)){setError("Enter exactly six digits to spotlight a PIN.");return}try{const r=await pinRisk(pin),state=String(r.state_normalized||"");if(state&&STATE_CENTROIDS[state])setSpotlight({pin,state});else setError("PIN risk returned no mappable state.")}catch(e){setError(e instanceof Error?e.message:"PIN risk unavailable")}}
 function download(){const url=URL.createObjectURL(new Blob([deserts.join("\n")],{type:"text/plain"})),a=document.createElement("a");a.href=url;a.download=`desert_states_${spec}.txt`;a.click();URL.revokeObjectURL(url)}
 return <div className="dm-shell"><aside className="dm-side"><div className="dm-brand"><Compass/><div><b>CareCompass — India</b><small>Healthcare intelligence platform</small></div></div><div className="dm-health"><small>System health</small><b><i/>{ok===null?"Checking…":ok?"All systems operational":"API unavailable"}</b></div><nav><Link href="/">Overview</Link><Link href="/">Facility Map</Link><Link className="active" href="/desert-map"><Map/>Crisis Map</Link><a>High Risk</a><a>Specialties</a></nav><div className="dm-side-filter"><small>Map filter</small><div><button className="active">State / Region</button><button disabled>City</button></div><select multiple value={selected} onChange={e=>setSelected([...e.target.selectedOptions].map(x=>x.value))} aria-label="Filter states"><option value="" disabled>All states / regions</option>{INDIA_STATES.map(x=><option key={x}>{x}</option>)}</select><button onClick={()=>setSelected([])}>Clear state filter</button></div><div className="dm-status"><small>Data layers</small>{["Policy coverage","PIN risk","Trust verification"].map(x=><span key={x}><Check/>{x}</span>)}</div></aside>
 <main className="dm-main"><header className="dm-top"><div><b>Coverage Dashboard</b><small>Facility coverage, distribution, and access metrics across India</small></div><div className="dm-top-actions"><ThemeToggle/><span><i/>Live</span></div></header><nav className="dm-nav"><Link href="/">Triage & Matching</Link><Link href="/mission-planner">Mission Planner</Link><Link className="active" href="/desert-map">Desert Map</Link></nav><section className="dm-content"><div className="dm-heading"><div><h1>Medical Desert Crisis Map</h1><p>PIN-code and state-level coverage intelligence — darker risk signals indicate lower specialty access.</p></div><span><AlertTriangle/>Highest-risk deserts</span></div>
 <div className="dm-modes">{([{id:"coverage",label:"Coverage Gap View",desc:"Red gaps · green covered"},{id:"hotspot",label:"Specialty Hotspot View",desc:"Blue supply concentration"},{id:"trust",label:"Trust Verified Facilities",desc:"Latest triage facilities"}] as const).map(x=><button key={x.id} className={mode===x.id?"active":""} onClick={()=>setMode(x.id)}><i/ ><b>{x.label}</b><small>{x.desc}</small></button>)}</div>
 <section className="dm-filters"><label><span>Specialty</span><select value={spec} onChange={e=>setSpec(e.target.value)}>{SPECS.map(x=><option key={x}>{x}</option>)}</select></label><label><span>Aggregation level</span><div className="dm-segment"><button className={level==="state"?"active":""} onClick={()=>setLevel("state")}>State</button><button className={level==="pin"?"active":""} onClick={()=>setLevel("pin")}>PIN</button></div></label>{level==="pin"&&<label className="dm-pin"><span>Optional PIN spotlight</span><div><input value={pin} maxLength={6} onChange={e=>setPin(e.target.value.replace(/\D/g,""))} placeholder="800001"/><button onClick={locatePin}><MapPin/>Locate</button></div></label>}</section>
 {error&&<div className="dm-error"><AlertTriangle/>{error}</div>}<div className="dm-metrics"><Metric n={deserts.length} label="High-risk states" tone="red" icon={<AlertTriangle/>}/><Metric n={pins.length} label="PIN codes — zero coverage" tone="orange" icon={<MapPin/>}/><Metric n={deserts.length+shownCovered.length} label="States analyzed" icon={<BarChart3/>}/><Metric n={data?.desert_pin_ratio_interval?Math.round(Number(data.desert_pin_ratio_interval.point||0)*100):0} suffix="%" label="Average desert share" tone="blue" icon={<ShieldCheck/>}/></div>
 <div className="dm-grid"><section className="dm-map-card"><header><div><b>Risk intensity by state</b><small>Circle size = estimated PIN pressure · color = coverage status</small></div>{busy&&<LoaderCircle className="spin"/>}</header><LeafletMap mode={mode} deserts={deserts} covered={shownCovered} pinCounts={pinCounts} trustPins={trustPins} spotlight={spotlight}/><div className="dm-legend"><b>Map layers</b><span><i className="red"/>Coverage gap</span><span><i className="green"/>Covered</span><span><i className="amber"/>Review facility</span></div></section><aside className="dm-ranking"><header><b>Medical desert regions</b><small>Current specialty and filters</small></header><div>{deserts.length?deserts.map((state,i)=><article key={state}><strong>{i+1}</strong><p><b>{state}</b><span>{pinCounts[state]||0} estimated desert PINs</span></p><em>High risk</em></article>):<p className="dm-none">No desert state returned for this selection.</p>}</div></aside></div>
 <section className="dm-bottom"><div><h2>Coverage summary</h2><p>Centroid circles are geographic indicators. Pressure points are deterministic density proxies, not individual facilities.</p></div><button onClick={download}><Download/>Download desert states</button><details><summary>Desert states ({deserts.length})</summary>{deserts.map(x=><span className="desert" key={x}>{x}</span>)}</details><details><summary>Covered states ({shownCovered.length})</summary>{shownCovered.map(x=><span key={x}>{x}</span>)}</details>{pins.length>0&&<details><summary>Desert PINs ({Math.min(120,pins.length)} shown)</summary>{pins.slice(0,120).map(x=><span className="desert" key={x}>{x}</span>)}</details>}</section></section></main></div>}
function Metric({n,suffix="",label,tone="green",icon}:{n:number;suffix?:string;label:string;tone?:string;icon:React.ReactNode}){return <article className={`dm-metric ${tone}`}><div>{icon}</div><p><b>{n.toLocaleString()}{suffix}</b><span>{label}</span></p></article>}
function cleanStates(v:unknown){return Array.isArray(v)?[...new Set(v.map(String).filter(x=>INDIA_STATES.includes(x)))]:[]}function distribute(states:string[],total:number){const out:Record<string,number>={};states.forEach((s,i)=>out[s]=Math.floor(total/states.length)+(i<total%states.length?1:0));return out}
function loadTrustPins():TrustPin[]{try{const x=JSON.parse(localStorage.getItem("carecompass-last-match")||"{}"),search=Array.isArray(x.search_result)?x.search_result:[],trust=Array.isArray(x.trust_artifacts?.per_facility)?x.trust_artifacts.per_facility:[];return trust.flatMap((t:Json)=>{const s=search.find((r:Json)=>String(r.name)===String(t.facility))||{},lat=Number(s.latitude??s.lat),lon=Number(s.longitude??s.lon);return Number.isFinite(lat)&&Number.isFinite(lon)?[{name:String(t.facility),lat,lon,score:Number(t.combined_trust_0_1||.5),verdict:String(t.final_verdict||"REVIEW"),flags:Array.isArray(t.all_flags)?t.all_flags.map(String):[]}]:[]})}catch{return[]}}
