"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { Activity, AlertTriangle, BarChart3, Bell, Check, ChevronDown, CircleGauge, ClipboardList, Compass, Database, Download, FileWarning, Gauge, LoaderCircle, MapPin, Moon, Search, ShieldCheck, Sparkles, Target, X } from "lucide-react";
import { health, pinRisk, policyDeserts } from "@/lib/api";
import ThemeToggle from "./ThemeToggle";

const SPECIALTIES = ["emergency","cardiology","ophthalmology","orthopedics","obgyn","pediatrics","oncology","neurology","dialysis","trauma","icu","surgery","dentistry","psychiatry","neonatology","Custom…"];
const STATES = ["Andaman and Nicobar Islands","Andhra Pradesh","Arunachal Pradesh","Assam","Bihar","Chandigarh","Chhattisgarh","Dadra and Nagar Haveli and Daman and Diu","Delhi","Goa","Gujarat","Haryana","Himachal Pradesh","Jammu and Kashmir","Jharkhand","Karnataka","Kerala","Ladakh","Lakshadweep","Madhya Pradesh","Maharashtra","Manipur","Meghalaya","Mizoram","Nagaland","Odisha","Puducherry","Punjab","Rajasthan","Sikkim","Tamil Nadu","Telangana","Tripura","Uttar Pradesh","Uttarakhand","West Bengal"];
type Json = Record<string, any>;
const pct = (value: unknown) => `${Math.round(Number(value || 0) * 100)}%`;

export default function MissionPlanner() {
  const [systemOk,setSystemOk]=useState<boolean|null>(null);
  const [specialty,setSpecialty]=useState("emergency"); const [custom,setCustom]=useState(""); const [level,setLevel]=useState<"pin"|"state">("pin");
  const [report,setReport]=useState<Json|null>(null); const [busy,setBusy]=useState(false); const [error,setError]=useState("");
  const [pin,setPin]=useState(""); const [risk,setRisk]=useState<Json|null>(null); const [pinBusy,setPinBusy]=useState(false);
  const [flagged,setFlagged]=useState<Json[]>([]);
  useEffect(()=>{health().then(x=>setSystemOk(Boolean(x.ok))).catch(()=>setSystemOk(false));try{const saved=JSON.parse(localStorage.getItem("carecompass-last-match")||"{}");const rows=saved?.trust_artifacts?.per_facility;setFlagged(Array.isArray(rows)?rows.filter((x:Json)=>["SUSPICIOUS","REVIEW"].includes(String(x.final_verdict))):[])}catch{}},[]);
  const activeSpecialty=(specialty==="Custom…"?custom:specialty).trim()||"emergency";
  const deserts=useMemo(()=>cleanStates(report?.desert_states),[report]);
  const covered=useMemo(()=>STATES.filter(state=>!deserts.includes(state)),[deserts]);
  const pins=useMemo(()=>(Array.isArray(report?.desert_pins)?report.desert_pins:[]).map(String).filter(x=>x&&x!=="null"&&x!=="None"),[report]);
  const wilson=report?.desert_pin_ratio_interval as Json|undefined;
  async function analyze(){setBusy(true);setError("");try{setReport(await policyDeserts(activeSpecialty,level))}catch(e){setError(e instanceof Error?e.message:"Analysis failed")}finally{setBusy(false)}}
  async function assessPin(){if(!/^\d{6}$/.test(pin)){setError("Please enter exactly 6 digits for the PIN code.");return}setPinBusy(true);setError("");try{setRisk(await pinRisk(pin))}catch(e){setError(e instanceof Error?e.message:"PIN assessment failed")}finally{setPinBusy(false)}}
  return <div className="mp-shell">
    <aside className="mp-sidebar"><div className="mp-brand"><span><Compass/></span><div><b>CareCompass</b><small>India</small></div></div><div className={`mp-health ${systemOk===false?"down":""}`}><small>System health</small><b><i/>{systemOk===null?"Checking services…":systemOk?"All systems operational":"API unavailable"}</b></div><button className="mp-new" onClick={()=>{setReport(null);setRisk(null);setPin("")}}><Target/>New analysis</button><nav><Link href="/">Referral Copilot</Link><Link className="active" href="/mission-planner"><ClipboardList/>Mission Planner</Link><Link href="/desert-map">Desert Map</Link></nav><div className="mp-agents"><small>AI model status</small><b>{systemOk?"Policy services online":"Check backend"}</b>{["Policy Checker","Geospatial Engine","Trust Validator","Data Extractor"].map(x=><span key={x}><Check/>{x}</span>)}</div></aside>
    <main className="mp-workspace"><header className="mp-top"><nav><Link className="active" href="/mission-planner">Mission Planner</Link></nav><div><ThemeToggle/><button><Bell/></button><span>UI</span><p><b>Umair Imran</b><small>Clinician / NGO</small></p><ChevronDown/></div></header>
      <section className="mp-page"><div className="mp-title"><div><span>Policy and outreach intelligence</span><h1>Mission Planner</h1><p>Identify specialty coverage gaps, quantify uncertainty, and prioritize healthcare access missions.</p></div><button onClick={()=>window.print()} disabled={!report}><Download/>Export planning report</button></div>
        <section className="mp-snapshot"><div className="mp-section-head"><div><h2>Dataset trust snapshot</h2><p>Verified counts from the cleaning pipeline. Quarantined artifacts are excluded by the backend.</p></div><ShieldCheck/></div><div className="mp-metrics"><Metric n="10,002" label="Total facilities" icon={<Database/>}/><Metric n="9,866" label="Valid PIN codes" icon={<MapPin/>}/><Metric n="136" label="Invalid PIN codes" tone="amber" icon={<FileWarning/>}/><Metric n="31" label="Quarantined records" tone="red" icon={<AlertTriangle/>}/></div></section>
        <section className="mp-filter-card"><div><span>Specialty</span><select value={specialty} onChange={e=>setSpecialty(e.target.value)}>{SPECIALTIES.map(x=><option key={x}>{x}</option>)}</select></div>{specialty==="Custom…"&&<div><span>Custom specialty</span><input value={custom} onChange={e=>setCustom(e.target.value)} placeholder="e.g. neonatology"/></div>}<div><span>Granularity</span><div className="mp-segment"><button className={level==="pin"?"active":""} onClick={()=>setLevel("pin")}>PIN</button><button className={level==="state"?"active":""} onClick={()=>setLevel("state")}>State</button></div></div><button className="mp-run" onClick={analyze} disabled={busy}>{busy?<LoaderCircle className="spin"/>:<Sparkles/>}{busy?"Analyzing coverage…":"Run desert analysis"}</button></section>
        {error&&<div className="mp-error"><AlertTriangle/>{error}<button onClick={()=>setError("")}><X/></button></div>}
        {!report?<EmptyAnalysis onRun={analyze}/>:<>
          <div className="mp-result-metrics"><Metric n={String(deserts.length)} label="Desert states" tone="red" icon={<AlertTriangle/>}/><Metric n={String(pins.length)} label="Desert PINs" tone="amber" icon={<MapPin/>}/><Metric n={String(covered.length)} label="Covered states" icon={<ShieldCheck/>}/><Metric n={wilson?pct(wilson.point):"—"} label="Estimated desert share" tone="purple" icon={<Gauge/>}/></div>
          <div className="mp-dashboard-grid"><section className="mp-panel mp-coverage"><PanelTitle title="Coverage by state" sub={`${activeSpecialty} · ${level.toUpperCase()} analysis`} icon={<BarChart3/>}/><CoverageBars deserts={deserts} covered={covered}/><div className="mp-state-columns"><StateList title="No coverage (desert)" items={deserts} tone="desert"/><StateList title="Has coverage" items={covered} tone="covered"/></div></section><section className="mp-panel"><PanelTitle title="Desert vs covered" sub="State distribution" icon={<CircleGauge/>}/><Donut desert={deserts.length} covered={covered.length}/></section></div>
          {wilson&&<section className="mp-panel mp-wilson"><PanelTitle title="Statistical confidence — Wilson score" sub="Uncertainty interval for the true desert proportion; not a clinical effect size." icon={<Activity/>}/><Wilson data={wilson}/></section>}
          {level==="pin"&&wilson?.n&&<section className="mp-panel"><PanelTitle title="PIN coverage composition" sub="Desert versus covered PINs in the analyzed sample" icon={<BarChart3/>}/><Stacked data={wilson}/></section>}
          {Array.isArray(report.citations)&&report.citations.length>0&&<section className="mp-panel"><PanelTitle title="Policy analysis citations" sub="Backend evidence receipts" icon={<ShieldCheck/>}/><div className="mp-citations">{report.citations.slice(0,5).map((c:Json,i:number)=><div key={i}><b>{String(c.source||"Policy evidence")}</b><span>{String(c.evidence_snippet||c.field||"Evidence returned by policy analysis")}</span><em>{pct(c.confidence)}</em></div>)}</div></section>}
          <FlaggedFacilities rows={flagged}/>
        </>}
        <section className="mp-pin"><div><span>Local access assessment</span><h2>PIN code risk assessment</h2><p>Inspect facility availability, high-trust share, contrast reasons, and sample facilities for one six-digit PIN.</p></div><div><input inputMode="numeric" maxLength={6} value={pin} onChange={e=>setPin(e.target.value.replace(/\D/g,""))} placeholder="e.g. 800001"/><button onClick={assessPin} disabled={pinBusy}>{pinBusy?<LoaderCircle className="spin"/>:<Search/>}Assess PIN risk</button></div></section>
        {risk&&!risk.error&&<PinResult risk={risk} pin={pin}/>}<footer className="mp-footer"><ShieldCheck/><p><b>Mission Planner is optimized for policy and outreach planning.</b><span>Decision support only—not a clinical decision tool. Human review is required.</span></p><div><small>Data source</small><b>Unity Catalog</b></div><div><small>Analysis</small><b>Policy + Geospatial</b></div></footer>
      </section>
    </main>
  </div>;
}

function Metric({n,label,tone="green",icon}:{n:string;label:string;tone?:string;icon:React.ReactNode}){return <article className={`mp-metric ${tone}`}><div><strong>{n}</strong><span>{label}</span></div>{icon}</article>}
function PanelTitle({title,sub,icon}:{title:string;sub:string;icon:React.ReactNode}){return <header className="mp-panel-title"><div>{icon}<p><b>{title}</b><span>{sub}</span></p></div></header>}
function StateList({title,items,tone}:{title:string;items:string[];tone:string}){return <div className={`mp-state-list ${tone}`}><h3>{title}<b>{items.length}</b></h3><div>{items.length?items.map(x=><span key={x}>{x}</span>):<p>No states returned in this category.</p>}</div></div>}
function CoverageBars({deserts,covered}:{deserts:string[];covered:string[]}){const rows=[...covered.map(state=>({state,covered:true})),...deserts.map(state=>({state,covered:false}))];return <div className="mp-coverage-chart" role="img" aria-label="Coverage status by Indian state"><div className="mp-chart-legend"><span><i className="covered"/>Has coverage</span><span><i className="desert"/>No coverage (desert)</span></div><div className="mp-bar-scroll">{rows.map(row=><div className="mp-state-bar" key={row.state}><b title={row.state}>{row.state}</b><span className={row.covered?"covered":"desert"}><i>{row.covered?"Has coverage":"No coverage"}</i></span></div>)}</div></div>}
function Donut({desert,covered}:{desert:number;covered:number}){const total=desert+covered||1;const d=Math.round(desert/total*100);return <div className="mp-donut-wrap"><div className="mp-donut" style={{background:`conic-gradient(#ef4d68 0 ${d}%,#16d596 ${d}% 100%)`}}><span><b>{100-d}%</b>covered</span></div><div className="mp-donut-key"><span><i className="desert"/>Desert states <b>{desert}</b></span><span><i className="covered"/>Covered states <b>{covered}</b></span></div></div>}
function Wilson({data}:{data:Json}){const point=Number(data.point||0),lo=Number(data.low_95||0),hi=Number(data.high_95||0);return <div className="mp-confidence"><div className="mp-confidence-labels"><span>0%</span><b>95% confidence interval: {pct(lo)}–{pct(hi)}</b><span>100%</span></div><div className="mp-confidence-track"><i style={{left:`${lo*100}%`,width:`${Math.max(1,(hi-lo)*100)}%`}}/><b style={{left:`${point*100}%`}}/></div><div className="mp-confidence-copy"><strong>{pct(point)}</strong><p>Estimated desert proportion<span>Based on {Number(data.n||0).toLocaleString()} observations; {Number(data.k||0).toLocaleString()} classified as desert.</span></p></div></div>}
function Stacked({data}:{data:Json}){const n=Number(data.n||0),k=Number(data.k||0),d=n?k/n*100:0;return <div className="mp-stack"><div><span style={{width:`${d}%`}}>{k.toLocaleString()} desert</span><b style={{width:`${100-d}%`}}>{Math.max(0,n-k).toLocaleString()} covered</b></div><p>Total analyzed: {n.toLocaleString()} PIN records</p></div>}
function EmptyAnalysis({onRun}:{onRun:()=>void}){return <section className="mp-empty"><span><ClipboardList/></span><h2>Build your first coverage mission</h2><p>Select a specialty and granularity. The existing policy and geospatial backend will identify deserts and calculate statistical confidence.</p><button onClick={onRun}><Sparkles/>Analyze selected specialty</button></section>}
function PinResult({risk,pin}:{risk:Json;pin:string}){const w=risk.high_trust_wilson as Json|undefined;const samples=Array.isArray(risk.sample_facilities)?risk.sample_facilities:[];const reasons=Array.isArray(risk.contrast_reasons)?risk.contrast_reasons:[];return <section className="mp-pin-result"><div className="mp-panel"><PanelTitle title={`PIN ${pin} risk profile`} sub="Local facility evidence" icon={<MapPin/>}/><Metric n={String(risk.facility_count??"—")} label="Facilities in PIN" icon={<Database/>}/>{w&&<Wilson data={w}/>}</div><div className="mp-panel"><PanelTitle title="Risk factors and sample facilities" sub="Factors returned by the policy backend" icon={<AlertTriangle/>}/>{reasons.length?<ul>{reasons.map((x:string)=><li key={x}>{humanize(x)}</li>)}</ul>:<p className="mp-muted">No contrast risk factors returned.</p>}{samples.length>0&&<div className="mp-table"><table><thead><tr>{Object.keys(samples[0]).map(x=><th key={x}>{humanize(x)}</th>)}</tr></thead><tbody>{samples.slice(0,10).map((row:Json,i:number)=><tr key={i}>{Object.keys(samples[0]).map(x=><td key={x}>{String(row[x]??"—")}</td>)}</tr>)}</tbody></table></div>}</div></section>}
function cleanStates(value:unknown){return Array.isArray(value)?[...new Set(value.map(String).map(x=>x.trim()).filter(x=>STATES.includes(x)))]:[]}
function humanize(value:string){return value.replace(/[_-]/g," ").replace(/\b\w/g,x=>x.toUpperCase())}
function FlaggedFacilities({rows}:{rows:Json[]}){return <section className="mp-panel mp-flagged"><PanelTitle title="Flagged facilities" sub="From the latest multi-agent truth verification" icon={<AlertTriangle/>}/>{rows.length?<><div className="mp-flag-head"><span>{rows.length} facilities require planner review</span><button onClick={()=>downloadFlagged(rows)}><Download/>Download flagged facilities (CSV)</button></div><div className="mp-table"><table><thead><tr><th>Facility</th><th>Trust</th><th>Verdict</th><th>Issues</th></tr></thead><tbody>{rows.slice(0,20).map((f,i)=><tr key={`${String(f.facility)}-${i}`}><td>{String(f.facility||"—")}</td><td>{pct(f.combined_trust_0_1)}</td><td><span className={`mp-verdict ${String(f.final_verdict).toLowerCase()}`}>{String(f.final_verdict||"—")}</span></td><td className="mp-issues">{(Array.isArray(f.all_flags)?f.all_flags:[]).slice(0,2).join("; ")||"—"}</td></tr>)}</tbody></table></div></>:<div className="mp-no-flagged"><ShieldCheck/><div><b>No stored truth-verification facility list</b><span>Run Triage & Matching once, then return here. The latest REVIEW and SUSPICIOUS facilities will appear automatically.</span></div><Link href="/">Open Triage & Matching</Link></div>}</section>}
function downloadFlagged(rows:Json[]){const quote=(value:unknown)=>`"${String(value??"").replace(/"/g,'""')}"`;const csv=["Facility,Trust,Verdict,Issues",...rows.map(f=>[f.facility,pct(f.combined_trust_0_1),f.final_verdict,(Array.isArray(f.all_flags)?f.all_flags:[]).slice(0,2).join("; ")].map(quote).join(","))].join("\n");const url=URL.createObjectURL(new Blob([csv],{type:"text/csv;charset=utf-8"}));const link=document.createElement("a");link.href=url;link.download="flagged_facilities.csv";link.click();URL.revokeObjectURL(url)}
